### ISSUE TITLE
render result has some noises

### ISSUE THREAD

**Issue by polluxll** [Twinklebear/webgl-volume-raycaster#1]
I add a new data for sample, and set volDims = [172, 128, 12],this is the result picture.
![volumn](https://user-images.githubusercontent.com/5866132/54329199-a23e6380-464b-11e9-84ae-3387c5623d94.png)

**Comment by Twinklebear** [comment]
I do use a [hash](https://github.com/Twinklebear/webgl-volume-raycaster/blob/master/js/shader-srcs.js#L51) to add some per-pixel offset and noise which you can try disabling, but without that you'll see some more structured artifact from the sampling. That might be similar to what you see there.

It could also be due to the small size of the volume, just 12 voxels along z is pretty small. So you might be able to change the [`volume_scale`](https://github.com/Twinklebear/webgl-volume-raycaster/blob/master/js/shader-srcs.js#L7) uniform to resize it properly. Is it a subset of some larger volume? Or it has some voxel scaling that should be applied?

**Comment by polluxll** [comment]
Very thanks for reply,the data from weather forecasting, it has only 12 levles on z axis.
A curved shape  appears when I changed the volume_scale .
var volScale = [volDims[0] / longestAxis, volDims[1] / longestAxis,
        volDims[2] / longestAxis/10
    ];
![volumn](https://user-images.githubusercontent.com/5866132/54401396-7500bc80-4702-11e9-93be-2af55e8999dd.png)

**Comment by Twinklebear** [comment]
Interesting, that my be more likely to be some aliasing effects from the camera ray samples. Since I take a fixed step size, you can actually see this without the hashing enabled as some kind of half-spheres along the dataset. The hash helps break this up and replace the aliasing with noise, but it might not work as well for such thin datasets.

**Comment by polluxll** [comment]
Finally,I use a linear interpolation for my data on z axis.
The webgl2 cann't be supported by all browsers(https://caniuse.com/#search=webgl2), does this code can be used by weblg1?

**Comment by Twinklebear** [comment]
Unfortunately no, this requires WebGL2 for 3D texture support, since they weren't available in WebGL1. It is possible to work around this by splitting the 3D texture into a bunch of 2D slices instead and putting them in a 2D texture array (I think this is supported on WebGL1?). However, you'll have to manually do the interpolation between slices since you won't get the trilinear interpolation done for you now (since they're separate 2D textures). This site http://www.lebarba.com/ has a write up on how it works, you can still follow the same method I use for creating the rays and raymarching, but will want to use their approach for sampling the 2D texture array as a "volume" instead.

**Comment by polluxll** [comment]
So,I just need to replace texture function by sampleVolume function on reference
(https://github.com/lebarba/WebGLVolumeRendering/blob/master/Web/Index.html) ,
and convert data to  a png image file with all the Z slices one next to the other.
![volumn](https://user-images.githubusercontent.com/5866132/54573113-de940a00-4a25-11e9-989c-4f7e24272bd2.png)

**Comment by Twinklebear** [comment]
Exactly, then you load those as a single 2d texture and sample them with their function. One thing you might want to be careful about is that if you don't put a border row/column of empty pixels around each slice you could see some artifacts at the edges of the slices where you end up interpolating with voxels from the following slice.

**Comment by polluxll** [comment]
I changing the code to webgl1,but an unsolvable problem happend !!!!

for (float t = t_hit.x; t < t_hit.y; t += dt) {}

ERROR: 0:66: 't' : Loop index cannot be initialized with non-constant expression

**Comment by Twinklebear** [comment]
Ah shoot, I forgot that was still a restriction in WebGL1. You'll have to change it to take a fixed number of samples, like:

```glsl
for (int i = 0; i < MAX_STEPS; ++i) {
}
```

and then adjust dt so that it steps through the whole volume after MAX_STEPS steps, [here](https://github.com/Twinklebear/webgl-volume-raycaster/blob/master/js/shader-srcs.js#L67)

```glsl
vec3 dt_vec = 1.0 / (vec3(MAX_STEPS) * abs(ray_dir));
```

I think `MAX_STEPS` has to be some hardcoded constant. You could also make it really high and then just check if `t >= t_hit.y` and break out of the loop:

```glsl
for (int i = 0; i < MAX_STEPS; ++i) {
    if (t >= t_hit.y) {
        break;
    }

    // at the end of the loop, advance t
    t += dt;
}
```

**Comment by polluxll** [comment]
Thanks very much for your guidance.

**Comment by Twinklebear** [comment]
Happy to help! If you've got stuff working I'll close this issue

**Comment by polluxll** [comment]
I use neghip data(neghip_64x64x64_uint8.raw) in my code as your gudiance,but it still cann't work!

**the javascript code for 2D textures**
   var xstep = 8;
    var ystep = 64 / xstep;
    var width = 64 * xstep;
    var height = 64 * ystep;
    var valueArray = new Uint8Array(width * height * 4);
    var i = 0;
    var z = 0;
    var realPosX, realPosY, realIndex;
    for (; z < 64; z++) {
        var y = 0;
        for (; y < 64; y++) {
            var x = 0;
            var yPos = 64 - y - 1;
            for (; x < 64; x++) {
                realPosX = x + (z % xstep) * 64;
                realPosY = yPos + Math.floor(z / xstep) * 64;
                realIndex = realPosX + realPosY * width;
                realIndex *= 4;
                var uint8Value = Math.floor(textData[i]);  //textData from neghip_64x64x64_uint8.raw
                valueArray[realIndex] = uint8Value;
                valueArray[realIndex + 1] = uint8Value;
                valueArray[realIndex + 2] = uint8Value;
                valueArray[realIndex + 3] = uint8Value;
                i++;
            }
        }
    }
    var volDims = [64, 64, 64];

    var tex = gl.createTexture();
    gl.activeTexture(gl.TEXTURE0);
    gl.bindTexture(gl.TEXTURE_2D, tex);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, width, height, 0, gl.RGBA, gl.UNSIGNED_BYTE, valueArray);


**the webgl1 code** 

precision mediump float;
uniform highp sampler2D volume;
uniform highp sampler2D colormap;
uniform ivec3 volume_dims;
uniform float dt_scale;

varying vec3 vray_dir;
varying vec3 transformed_eye;

vec2 intersect_box(vec3 orig, vec3 dir) {
	const vec3 box_min = vec3(0);
	const vec3 box_max = vec3(1);
	vec3 inv_dir = 1.0 / dir;
	vec3 tmin_tmp = (box_min - orig) * inv_dir;
	vec3 tmax_tmp = (box_max - orig) * inv_dir;
	vec3 tmin = min(tmin_tmp, tmax_tmp);
	vec3 tmax = max(tmin_tmp, tmax_tmp);
	float t0 = max(tmin.x, max(tmin.y, tmin.z));
	float t1 = min(tmax.x, min(tmax.y, tmax.z));
	return vec2(t0, t1);
}

const vec3 rand_constants = vec3(12.9898, 78.233, 4375.85453);
float rand(const vec2 co) {
	float t = dot(rand_constants.xy, co);
	return fract(sin(t) * (rand_constants.z + t));
}

const float zdef=63.0;
const float xstep=8.0;
const float ystep=8.0;
float sampleAs3DTexture(vec3 texCoord){
	float colorSlice1, colorSlice2;
	vec2 texCoordSlice1, texCoordSlice2;
	float zSliceNumber1 = floor(texCoord.z  * zdef);
	float zSliceNumber2 = min( zSliceNumber1 + 1.0, zdef);

	texCoord.xy /= vec2(xstep,ystep);

	texCoordSlice1 = texCoordSlice2 = texCoord.xy;

	texCoordSlice1.x += (mod(zSliceNumber1, xstep ) / xstep);
	texCoordSlice1.y += floor((zdef - zSliceNumber1) / ystep) / ystep;
	texCoordSlice1.y=1.0-texCoordSlice1.y;

	texCoordSlice2.x += (mod(zSliceNumber2, xstep ) / xstep);
	texCoordSlice2.y += floor((zdef - zSliceNumber2) / ystep) / ystep;
	texCoordSlice2.y=1.0-texCoordSlice2.y;

	colorSlice1 = texture2D(volume, texCoordSlice1).r;
	colorSlice2 = texture2D(volume, texCoordSlice2).r;

    float zDifference = mod(texCoord.z * zdef, 1.0);

    return mix(colorSlice1, colorSlice2, zDifference) ;
}
const int MAX_STEPS=64;
void main(void) {
	vec3 ray_dir = normalize(vray_dir);
	vec2 t_hit = intersect_box(transformed_eye, ray_dir);
	if (t_hit.x > t_hit.y) {
		discard;
	}
	t_hit.x = max(t_hit.x, 0.0);
	vec3 dt_vec = 1.0 / (vec3(volume_dims) * abs(ray_dir));
	//vec3 dt_vec = 1.0 / (vec3(MAX_STEPS) * abs(ray_dir));
	float dt = dt_scale * min(dt_vec.x, min(dt_vec.y, dt_vec.z));
	float offset = rand(vec2(gl_FragCoord.x, 640.0 * gl_FragCoord.y));
	vec3 p = transformed_eye + (t_hit.x + offset * dt) * ray_dir;
	vec4 color;
	float t = t_hit.x;
	for (int i = 0; i < MAX_STEPS; ++i) {
		if (t >= t_hit.y) {
			break;
		}
		float val = sampleAs3DTexture(p);
		vec4 val_color = vec4(texture2D(colormap, vec2(val, 0.5)).rgb, val);
		color.rgb += (1.0 - color.a) * val_color.a * val_color.rgb;
		color.a += (1.0 - color.a) * val_color.a;
		if (color.a >= 0.95) {
			break;
		}
		p += ray_dir * dt;
		t += dt;
    }
	gl_FragColor=color;
}

![image](https://user-images.githubusercontent.com/5866132/55390750-70456080-556a-11e9-8f47-57206e2a29c1.png)

**Comment by polluxll** [comment]
Finally,I change the code to webgl1.0 , but there are still something wrong.
**the data file neghip_64x64x64_uint8.raw**
**the javascript code**    
   var xstep = 8;
    var ystep = 64 / xstep;
    var width = 64 * xstep;
    var height = 64 * ystep;
    var valueArray = new Uint8Array(width * height * 4);
    var i = 0;
    var z = 0;
    var realPosX, realPosY, realIndex;
    for (; z < 64; z++) {
        var y = 0;
        for (; y < 64; y++) {
            var x = 0;
            var yPos = 64 - y - 1;
            for (; x < 64; x++) {
                realPosX = x + (z % xstep) * 64;
                realPosY = yPos + Math.floor(z / xstep) * 64;
                realIndex = realPosX + realPosY * width;
                realIndex *= 4;
                //textData form neghip_64x64x64_uint8.raw
                var uint8Value = textData[i];
                valueArray[realIndex] = uint8Value;
                valueArray[realIndex + 1] = uint8Value;
                valueArray[realIndex + 2] = uint8Value;
                valueArray[realIndex + 3] = uint8Value;
                i++;
            }
        }
    }
    var volDims = [64, 64, 64];
    var tex = gl.createTexture();
    gl.activeTexture(gl.TEXTURE0);
    gl.bindTexture(gl.TEXTURE_2D, tex);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, width, height, 0, gl.RGBA, gl.UNSIGNED_BYTE, valueArray);

**the webgl 1.0 code**
var fragShader =
    `precision mediump float;
uniform highp sampler2D volume;
uniform highp sampler2D colormap;
uniform ivec3 volume_dims;
uniform float dt_scale;

varying vec3 vray_dir;
varying vec3 transformed_eye;

vec2 intersect_box(vec3 orig, vec3 dir) {
	const vec3 box_min = vec3(0);
	const vec3 box_max = vec3(1);
	vec3 inv_dir = 1.0 / dir;
	vec3 tmin_tmp = (box_min - orig) * inv_dir;
	vec3 tmax_tmp = (box_max - orig) * inv_dir;
	vec3 tmin = min(tmin_tmp, tmax_tmp);
	vec3 tmax = max(tmin_tmp, tmax_tmp);
	float t0 = max(tmin.x, max(tmin.y, tmin.z));
	float t1 = min(tmax.x, min(tmax.y, tmax.z));
	return vec2(t0, t1);
}

const vec3 rand_constants = vec3(12.9898, 78.233, 4375.85453);
float rand(const vec2 co) {
	float t = dot(rand_constants.xy, co);
	return fract(sin(t) * (rand_constants.z + t));
}

const float zdef=63.0;
const float xstep=8.0;
const float ystep=8.0;
float sampleAs3DTexture(vec3 texCoord){
	float colorSlice1, colorSlice2;
	vec2 texCoordSlice1, texCoordSlice2;
	float zSliceNumber1 = floor(texCoord.z  * zdef);
	float zSliceNumber2 = min( zSliceNumber1 + 1.0, zdef);

	texCoord.xy /= vec2(xstep,ystep);

	texCoordSlice1 = texCoordSlice2 = texCoord.xy;

	texCoordSlice1.x += (mod(zSliceNumber1, xstep ) / xstep);
	texCoordSlice1.y += floor((zdef - zSliceNumber1) / ystep) / ystep;
	texCoordSlice1.y=1.0-texCoordSlice1.y;

	texCoordSlice2.x += (mod(zSliceNumber2, xstep ) / xstep);
	texCoordSlice2.y += floor((zdef - zSliceNumber2) / ystep) / ystep;
	texCoordSlice2.y=1.0-texCoordSlice2.y;

	colorSlice1 = texture2D(volume, texCoordSlice1).r;
	colorSlice2 = texture2D(volume, texCoordSlice2).r;

    float zDifference = mod(texCoord.z * zdef, 1.0);

    return mix(colorSlice1, colorSlice2, zDifference);
}
const int MAX_STEPS=200;
void main(void) {
	vec3 ray_dir = normalize(vray_dir);
	vec2 t_hit = intersect_box(transformed_eye, ray_dir);
	if (t_hit.x > t_hit.y) {
		discard;
	}
	t_hit.x = max(t_hit.x, 0.0);
	vec3 dt_vec = 1.0 / (vec3(volume_dims) * abs(ray_dir));
	//vec3 dt_vec = 1.0 / (vec3(MAX_STEPS) * abs(ray_dir));
	float dt = dt_scale * min(dt_vec.x, min(dt_vec.y, dt_vec.z));
	float offset = rand(vec2(gl_FragCoord.x, 640.0 * gl_FragCoord.y));
	vec3 p = transformed_eye + (t_hit.x + offset * dt) * ray_dir;
	vec4 color;
	float t = t_hit.x;
	for (int i = 0; i < MAX_STEPS; ++i) {
		if (t >= t_hit.y) {
			break;
		}
		float val = sampleAs3DTexture(p);
		vec4 val_color = vec4(texture2D(colormap, vec2(val, 0.5)).rgb, val);
		color.rgb += (1.0 - color.a) * val_color.a * val_color.rgb;
		color.a += (1.0 - color.a) * val_color.a;
		if (color.a >= 0.95) {
			break;
		}
		p += ray_dir * dt;
		t += dt;
    }
	gl_FragColor=color;
}`;

![image](https://user-images.githubusercontent.com/5866132/55447924-65391180-55f8-11e9-84b3-78070bed38d1.png)
