### ISSUE TITLE
How to generate a file like bonsai_256x256x256_uint8.raw？

### ISSUE THREAD

**Issue by kt7456** [Twinklebear/webgl-volume-raycaster#11]
How to generate a file like bonsai_256x256x256_uint8.raw？

**Comment by Twinklebear** [comment]
You can write a program that outputs a binary file using the binary I/O mode of whatever language you're working in. With JS I guess you could populate a `Uint8Array` and put it into a `Blob` to save out. You can also do it in Python using binary I/O.

The original bonsai file comes from a 3D scanner. You can find other data sets to play with here: https://klacansky.com/open-scivis-datasets/

**Comment by kt7456** [comment]
> o

thanks！
