### ISSUE TITLE
How to display only one surface, a surface generated from any two points

### ISSUE THREAD

**Issue by kt7456** [Twinklebear/webgl-volume-raycaster#12]
How to display only one surface, a surface generated from any two points？
like below：
![1682932201533](https://user-images.githubusercontent.com/35618730/235433248-c66ee894-cd34-44aa-8cda-b68fe036983d.jpg)
![image](https://user-images.githubusercontent.com/35618730/235433359-5f276e9f-e30b-4f1b-b59f-f52697d92ffa.png)

**Comment by Twinklebear** [comment]
I don't remember (but based on OpenGL/Vulkan/DX12), I don't think WebGL supports "thick lines". So the `GL_LINE` primitive will just be a single pixel wide line, which won't look like the pictures you have here.

To draw a thick line or arrow like this you have to make a big rectangle (2 triangles) that cover the region you want the line to be in. Then you can draw some texture on top of it with your arrow (but it might look pixelated or stretched), or evaluate some function defining which pixels are in the arrow and not, coloring those in the arrow and discarding those that are not to get a higher quality result.
