### ISSUE TITLE
How to display only one slanted plane？

### ISSUE THREAD

**Issue by kt7456** [Twinklebear/webgl-volume-raycaster#13]
![235433248-c66ee894-cd34-44aa-8cda-b68fe036983d](https://user-images.githubusercontent.com/35618730/236595341-975deed2-4cd6-44e2-af7c-229ff5a2ae0d.jpg)
i mean cut into a face or a plane ，like below
![image](https://user-images.githubusercontent.com/35618730/236595328-51638b67-72b1-4f29-9180-63e4bed126f4.png)

**Comment by kt7456** [comment]
cut into slanted planes

**Comment by Twinklebear** [comment]
It sounds like you mean the same as https://github.com/Twinklebear/webgl-volume-raycaster/issues/9#issuecomment-1478817045 , to draw the volume texture on just a plane that cuts through it. You'd do as I mention in that comment, draw a plane and then look up its coordinates in the 3d volume to texture it with the volume texture

**Comment by kt7456** [comment]
i forget say thanks！
