### ISSUE TITLE
Wrong color when slice is small

### ISSUE THREAD

**Issue by kt7456** [Twinklebear/webgl-volume-raycaster#14]
Thin slices are rendered in the wrong color when adjusting the camera perspective
normal pic
![image](https://github.com/Twinklebear/webgl-volume-raycaster/assets/35618730/97360c2a-8c92-4120-9f7a-1afc70b98a8b)
wrong pic
![image](https://github.com/Twinklebear/webgl-volume-raycaster/assets/35618730/cfaf1c29-3f61-4b43-b3b1-2df978e7d767)

This is the thickness of the slice
![image](https://github.com/Twinklebear/webgl-volume-raycaster/assets/35618730/4308c2a1-8514-48fa-a52e-5274a92a2584)

**Comment by Twinklebear** [comment]
That's interesting, it seems like the blend equation or order might not be right? Are you drawing the map geometry first and then blending the slice on top?

**Comment by kt7456** [comment]
> > That's interesting, it seems like the blend equation or order might not be right? Are you drawing the map geometry first and then blending the slice on top?
> 
> Yes, but I have the same problem running your webgl example，when slice is small
