### ISSUE TITLE
I have several 2D images representing different depth,want to generate as volume data

### ISSUE THREAD

**Issue by kt7456** [Twinklebear/webgl-volume-raycaster#17]
I have several 2D images representing different depth, not from 3D scans but satellite acquisitions, is it possible to generate volume data for this project rendering?

**Comment by Twinklebear** [comment]
Yes, but whether it makes sense to render it as a volume depends on what's in those 2D images. A 3D volume is just a stack of 2D images, so you would just make a 3D volume with z = # of images, and populate each layer using the respective 2d image.

**Comment by kt7456** [comment]
thanks
