### ISSUE TITLE
Volume Raycasting in Cesium

### ISSUE THREAD

**Issue by polluxll** [Twinklebear/webgl-volume-raycaster#2]
I sent a mail to you,but was rejected by server!
 I want to add a CT scan data on Cesium,I've been doing it these days. I'm not sure why it's failing.Please give me some suggestions!

[Cesium.zip](https://github.com/Twinklebear/webgl-volume-raycaster/files/3124501/Cesium.zip)

References: https://cesiumjs.org/demos/VolumeRaycasting/
                   https://www.willusher.io/webgl/2019/01/13/volume-rendering-with-webgl

**Comment by Twinklebear** [comment]
Hey @polluxll , it probably bounced because the mail server probably doesn't allow sending .zip files for security reasons. I'm not sure I follow you question, are you trying to integrate the volume raycaster into Cesium? Or render some dataset from that post with the WebGL volume renderer?

**Comment by polluxll** [comment]
Finally,I want to integrate the volume raycaster into Cesium.I update the code in Cesium.zip file,I think the IntersectBox function doesn't work well on globe surface,and I sent you a new mail.
![cesium](https://user-images.githubusercontent.com/5866132/56856950-dde18280-6998-11e9-94c6-8a78cc3be640.png)

**Comment by Twinklebear** [comment]
This does look interesting! I sent a reply to your email, but since this project is focused on just rendering rectangular grid volumes I'll close this issue and we can discuss some over email.
