### ISSUE TITLE
Why is the direction reversed?

### ISSUE THREAD

**Issue by kt7456** [Twinklebear/webgl-volume-raycaster#5]
<img width="503" alt="1662432797606" src="https://user-images.githubusercontent.com/35618730/188537145-7fb6920b-1eb8-4acb-84bd-76cfa94a3891.png">
<img width="406" alt="1662432991117" src="https://user-images.githubusercontent.com/35618730/188537515-ac8922e1-a54f-4a73-aad2-2ed8e928d0f7.png">

Why is the direction reversed，
I am using mapboxgl，Guess what causes this? thanks！
this is demo address

**Comment by Twinklebear** [comment]
My guess is that mapboxgl is applying some y-flip the image, which you need to apply to the volume as well either when you render it or when you display the volume rendering above the map (if you're rendering to a texture and compositing that on top of the map)

**Comment by kt7456** [comment]
> My guess is that mapboxgl is applying some y-flip the image, which you need to apply to the volume as well either when you render it or when you display the volume rendering above the map (if you're rendering to a texture and compositing that on top of the map)

i dont know how to do ，please help me
