### ISSUE TITLE
how to open bonsai_256x256x256_uint8.raw with software

### ISSUE THREAD

**Issue by kt7456** [Twinklebear/webgl-volume-raycaster#8]
how to open bonsai_256x256x256_uint8.raw with software

**Comment by Twinklebear** [comment]
You can use ParaView https://www.paraview.org/ as described here: https://sciviz.xyz/2018/11/08/raw-files-in-paraview/

- Data scalar type: uint8/byte/char (whatever they have in the UI)
- Byte Order: little endian (doesn't matter for uint8)
- Data extent: [0, 255] for each entry for x/y/z

**Comment by kt7456** [comment]
> You can use ParaView https://www.paraview.org/ as described here: https://sciviz.xyz/2018/11/08/raw-files-in-paraview/
> 
> * Data scalar type: uint8/byte/char (whatever they have in the UI)
> * Byte Order: little endian (doesn't matter for uint8)
> * Data extent: [0, 255] for each entry for x/y/z

thanks！
